name: ${project.name}
description: ${project.description}
main: org.retromc.socials.SocialsPlugin
version: ${project.version}
authors:
  - OldManYells
softdepend:
  - Essentials

commands:
  socials:
    description: Show configured social links.
    usage: /<command>
    aliases: [social]

permissions:
  poseidon.socials:
    description: Allows using /socials.
    default: op


links:
  - name: "§2Website§r§f"
    url: "https://retromc.org"
  - name: "§6Wiki§r§f"
    url: "https://wiki.retromc.org/"
  - name: "§9Discord§r§f"
    url: "https://discord.retromc.org/"
